FROM dylanmei/zeppelin:0.7.3

COPY . /tmp/pymichel

RUN chmod 700 /tmp/pymichel/docker/build_egg.sh
RUN /tmp/pymichel/docker/build_egg.sh

RUN chmod 700 /tmp/pymichel/docker/deploy-spark-job.sh
RUN /tmp/pymichel/docker/deploy-spark-job.sh

ENTRYPOINT /tmp/pymichel/docker/deploy-spark-job.sh 
